<a href="https://colab.research.google.com/github/Diya1506/Diya1506/blob/main/SecureSwipe.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
  from google.colab import files
uploaded= files.upload()
import pandas as pd
import io
df= pd.read_csv('cc fraud detection.csv')
print(df)
import numpy as np
!pip install scikit-learn

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
from sklearn.preprocessing import StandardScaler

Saving cc fraud detection.csv to cc fraud detection.csv
     Unnamed: 0  Customer_ID  A_1    A_2     A_3  A_4  A_5  A_6    A_7  A_8  \
0             0     15776156    1  22.08  11.460    2    4    4  1.585    0
1             1     15739548    0  22.67   7.000    2    8    4  0.165    0
2             2     15662854    0  29.58   1.750    1    4    4  1.250    0
3             3     15687688    0  21.67  11.500    1    5    3  0.000    1
4             4     15715750    1  20.17   8.170    2    6    4  1.960    1
..          ...          ...  ...    ...     ...  ...  ...  ...    ...  ...
685         685     15808223    1  31.57  10.500    2   14    4  6.500    1
686         686     15769980    1  20.67   0.415    2    8    4  0.125    0
687         687     15675450    0  18.83   9.540    2    6    4  0.085    1
688         688     15776494    0  27.42  14.500    2   14    8  3.085    1
689         689     15592412    1  41.00   0.040    2   10    4  0.040    0

     A_9  A_10  A_11  A_12  A_13  A_14  class
0      0     0     1     2   100  1213      0
1      0     0     0     2   160     1      0
2      0     0     1     2   280     1      0
3      1    11     1     2     0     1      1
4      1    14     0     2    60   159      1
..   ...   ...   ...   ...   ...   ...    ...
685    0     0     0     2     0     1      1
686    0     0     0     2     0    45      0
687    0     0     0     2   100     1      1
688    1     1     0     2   120    12      1
689    1     1     0     1   560     1      1

[690 rows x 17 columns]
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.10/dist-packages (1.2.2)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.25.2)
Requirement already satisfied: scipy>=1.3.2 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.11.4)
Requirement already satisfied: joblib>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (1.4.2)
Requirement already satisfied: threadpoolctl>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from scikit-learn) (3.5.0)

In [ ]:
# loading the dataset to a Pandas DataFrame
credit_card_data=pd.read_csv('/content/cc fraud detection.csv')

In [ ]:
# first 5 rows of the dataset
credit_card_data.head()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14,class
0,0,15776156,1,22.08,11.46,2,4,4,1.585,0,0,0,1,2,100,1213,0
1,1,15739548,0,22.67,7.00,2,8,4,0.165,0,0,0,0,2,160,1,0
2,2,15662854,0,29.58,1.75,1,4,4,1.250,0,0,0,1,2,280,1,0
3,3,15687688,0,21.67,11.50,1,5,3,0.000,1,1,11,1,2,0,1,1
4,4,15715750,1,20.17,8.17,2,6,4,1.960,1,1,14,0,2,60,159,1

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
credit_card_data.tail()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14,class
685,685,15808223,1,31.57,10.500,2,14,4,6.500,1,0,0,0,2,0,1,1
686,686,15769980,1,20.67,0.415,2,8,4,0.125,0,0,0,0,2,0,45,0
687,687,15675450,0,18.83,9.540,2,6,4,0.085,1,0,0,0,2,100,1,1
688,688,15776494,0,27.42,14.500,2,14,8,3.085,1,1,1,0,2,120,12,1
689,689,15592412,1,41.00,0.040,2,10,4,0.040,0,1,1,0,1,560,1,1

In [ ]:
# dataset informations
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 690 entries, 0 to 689
Data columns (total 17 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Unnamed: 0   690 non-null    int64
 1   Customer_ID  690 non-null    int64
 2   A_1          690 non-null    int64
 3   A_2          690 non-null    float64
 4   A_3          690 non-null    float64
 5   A_4          690 non-null    int64
 6   A_5          690 non-null    int64
 7   A_6          690 non-null    int64
 8   A_7          690 non-null    float64
 9   A_8          690 non-null    int64
 10  A_9          690 non-null    int64
 11  A_10         690 non-null    int64
 12  A_11         690 non-null    int64
 13  A_12         690 non-null    int64
 14  A_13         690 non-null    int64
 15  A_14         690 non-null    int64
 16  class        690 non-null    int64
dtypes: float64(3), int64(14)
memory usage: 91.8 KB

In [ ]:
# checking the number of missing values in each column
credit_card_data.isnull().sum()

Unnamed: 0     0
Customer_ID    0
A_1            0
A_2            0
A_3            0
A_4            0
A_5            0
A_6            0
A_7            0
A_8            0
A_9            0
A_10           0
A_11           0
A_12           0
A_13           0
A_14           0
class          0
dtype: int64

In [ ]:
# distribution of legit transactions and fraudulent transactions
credit_card_data['class'].value_counts()

class
0    383
1    307
Name: count, dtype: int64

**This dataset is balanced**

0-> normal transaction
1-> fraudulent transaction

In [ ]:
# separating the data for analysis
legit= credit_card_data[credit_card_data['class']==0]
fraud= credit_card_data[credit_card_data['class']==1]

In [ ]:
print(legit.shape)
print(fraud.shape)

(383, 17)
(307, 17)

In [ ]:
# compare the values for both transactions
credit_card_data.groupby('class').mean()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14
class,,,,,,,,,,,,,,,,
0,347.018277,1.568821e+07,0.684073,29.854230,3.839948,1.691906,6.140992,4.253264,1.257924,0.201044,0.224543,0.631854,0.443864,1.898172,199.412533,199.605744
1,341.358306,1.569330e+07,0.671010,33.706482,5.904951,1.859935,8.908795,5.241042,3.427899,0.925081,0.680782,4.605863,0.475570,1.967427,164.804560,2039.859935

under sampling
build a sample dataset containing similar distribution of legit transactions and fraudulent transactions
The number of fraudulent transactions->307

In [ ]:
legit_sample= legit.sample(n=307)

**concatenating two dataframes**

In [ ]:
new_dataset= pd.concat([legit_sample,fraud],axis=0)

In [ ]:
new_dataset.head()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14,class
464,464,15667934,0,57.58,2.000,2,1,1,6.5,0,1,1,0,2,0,11,0
568,568,15750545,0,45.00,4.585,2,4,8,1.0,0,0,0,1,1,240,1,0
620,620,15758477,1,26.92,2.250,2,3,5,0.5,0,0,0,1,2,640,4001,0
289,289,15672637,0,36.75,4.710,2,1,1,0.0,0,0,0,0,2,160,1,0
170,170,15684722,0,27.67,1.500,2,7,4,2.0,1,0,0,0,1,368,1,0

In [ ]:
new_dataset.tail()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14,class
684,684,15740356,1,43.00,0.29,1,13,8,1.750,1,1,8,0,2,100,376,1
685,685,15808223,1,31.57,10.50,2,14,4,6.500,1,0,0,0,2,0,1,1
687,687,15675450,0,18.83,9.54,2,6,4,0.085,1,0,0,0,2,100,1,1
688,688,15776494,0,27.42,14.50,2,14,8,3.085,1,1,1,0,2,120,12,1
689,689,15592412,1,41.00,0.04,2,10,4,0.040,0,1,1,0,1,560,1,1

In [ ]:
new_dataset['class'].value_counts()

class
0    307
1    307
Name: count, dtype: int64

In [ ]:
new_dataset.groupby('class').mean()

,Unnamed: 0,Customer_ID,A_1,A_2,A_3,A_4,A_5,A_6,A_7,A_8,A_9,A_10,A_11,A_12,A_13,A_14
class,,,,,,,,,,,,,,,,
0,342.013029,1.568950e+07,0.677524,29.386612,3.957736,1.710098,6.237785,4.244300,1.169495,0.192182,0.237785,0.628664,0.449511,1.899023,196.648208,208.074919
1,341.358306,1.569330e+07,0.671010,33.706482,5.904951,1.859935,8.908795,5.241042,3.427899,0.925081,0.680782,4.605863,0.475570,1.967427,164.804560,2039.859935

**spliting the data into features and targets**

In [ ]:
X= new_dataset.drop(columns='class', axis=1)
Y= new_dataset['class']

In [ ]:
print(X)

     Unnamed: 0  Customer_ID  A_1    A_2     A_3  A_4  A_5  A_6    A_7  A_8  \
464         464     15667934    0  57.58   2.000    2    1    1  6.500    0
568         568     15750545    0  45.00   4.585    2    4    8  1.000    0
620         620     15758477    1  26.92   2.250    2    3    5  0.500    0
289         289     15672637    0  36.75   4.710    2    1    1  0.000    0
170         170     15684722    0  27.67   1.500    2    7    4  2.000    1
..          ...          ...  ...    ...     ...  ...  ...  ...    ...  ...
684         684     15740356    1  43.00   0.290    1   13    8  1.750    1
685         685     15808223    1  31.57  10.500    2   14    4  6.500    1
687         687     15675450    0  18.83   9.540    2    6    4  0.085    1
688         688     15776494    0  27.42  14.500    2   14    8  3.085    1
689         689     15592412    1  41.00   0.040    2   10    4  0.040    0

     A_9  A_10  A_11  A_12  A_13  A_14
464    1     1     0     2     0    11
568    0     0     1     1   240     1
620    0     0     1     2   640  4001
289    0     0     0     2   160     1
170    0     0     0     1   368     1
..   ...   ...   ...   ...   ...   ...
684    1     8     0     2   100   376
685    0     0     0     2     0     1
687    0     0     0     2   100     1
688    1     1     0     2   120    12
689    1     1     0     1   560     1

[614 rows x 16 columns]

In [ ]:
print(Y)

464    0
568    0
620    0
289    0
170    0
      ..
684    1
685    1
687    1
688    1
689    1
Name: class, Length: 614, dtype: int64

**Train test Split**

In [ ]:
credit_card_data = pd.read_csv('/content/cc fraud detection.csv')
legit = credit_card_data[credit_card_data['class'] == 0]
fraud = credit_card_data[credit_card_data['class'] == 1]
legit_sample = legit.sample(n=307)
new_dataset = pd.concat([legit_sample, fraud], axis=0)
X = new_dataset.drop(columns='class', axis=1)
Y = new_dataset['class']
X_train, X_test, Y_train, Y_test= train_test_split(X,Y, test_size=0.2, stratify=Y, random_state=2)

In [ ]:
scaler= StandardScaler()
X_train= scaler.fit_transform(X_train)
X_test= scaler.transform(X_test)
print(X.shape, X_train.shape, X_test.shape)

(614, 16) (491, 16) (123, 16)

**Model training**

**Logistic Regression**

In [ ]:
model= LogisticRegression()

In [ ]:
# training the logistic regression model with training data
model = LogisticRegression()
model.fit(X_train, Y_train)

LogisticRegression()

**Model Evaluation**
**Accuracy Score**

In [ ]:
# accuracy of training data
X_train_prediction = model.predict(X_train)
X_test_prediction = model.predict(X_test)

training_accuracy = accuracy_score(Y_train, X_train_prediction)
test_accuracy = accuracy_score(Y_test, X_test_prediction)
precision = precision_score(Y_test, X_test_prediction)
recall = recall_score(Y_test, X_test_prediction)
f1 = f1_score(Y_test, X_test_prediction)
print(f'Accuracy on training data: {training_accuracy}')
print(f'Accuracy on test data: {test_accuracy}')
print(f'Precision: {precision}')
print(f'Recall: {recall}')
print(f'F1-score: {f1}')

Accuracy on training data: 0.8839103869653768
Accuracy on test data: 0.8617886178861789
Precision: 0.8333333333333334
Recall: 0.9016393442622951
F1-score: 0.8661417322834646

In [ ]:
print('accuracy on training data: ', training_accuracy)

accuracy on training data:  0.8839103869653768

In [ ]:
print('accuracy on test data: ',  test_accuracy)

accuracy on test data:  0.8617886178861789

Report for a ML project based on Credit Card fraud detection system using logistic regression with NumPy, Pandas, and scikit-learn:

**Project Title:** Logistic Regression for Classification and detection of legit and fraud transactions using NumPy, Pandas, and scikit-learn

**Objective:** To develop a logistic regression model to predict the number of credit card fraud transactions and the performance accuracy of the system using numerical features.



**Preprocessing:**

- Loaded dataset into a Pandas DataFrame
- Handled missing values using isnull().values() function
- Scaled numerical features using scikit-learn's StandardScaler

**Model Development:**

- Implemented logistic regression using scikit-learn's LogisticRegression class
- Evaluated model performance using metrics like accuracy, precision, recall, and F1-score

**Results:**

- **Accuracy of training data:** 0.8655804480651731
- **Accuracy of test data:** 0.9024390243902439
- **Precision:** 0.8888888888888888
- **Recall: **0.9180327868852459
- **F1-score:** 0.9032258064516128

**Conclusion:**

- The logistic regression model achieved 'good classification performance' using numerical features and scikit-learn's implementation.
- The model can be improved by exploring additional features, feature engineering, or alternative algorithms.

# New Section